const list = [
    {
        id: 1,
        title: "My First Book of Pencil Control",
        author: "by Wonder House Books | 25 April 2018",
        price: 89,
        img: "https://www.jogenii.com/cdn/shop/products/9788195147755_1_800x.jpg?v=1680202334",
        amount: 1,
    },
    {
        id: 2,
        title: "The Great Adventure",
        author: "by John Doe | 10 January 2020",
        price: 199,
        img: "https://kennyloggins.com/wp-content/uploads/2021/01/sdzookidsart-768x768.jpg",
        amount: 1,
    },
    {
        id: 3,
        title: "Learning React",
        author: "by Alex Banks and Eve Porcello | 1 March 2019",
        price: 299,
        img: "https://m.media-amazon.com/images/I/61NRpXmZR8S._AC_UF1000,1000_QL80_.jpg",
        amount: 1,
    },
    {
        id: 4,
        title: "JavaScript: The Good Parts",
        author: "by Douglas Crockford | 15 May 2008",
        price: 150,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSn2Sz7_kUX_sIKbc0RNMN7PbZKyqvsoBlCVQ&s",
        amount: 1,
    },
    {
        id: 5,
        title: "Clean Code",
        author: "by Robert C. Martin | 1 August 2008",
        price: 350,
        img: "https://m.media-amazon.com/images/I/41zoxjP9lcL._AC_SY200_QL15_.jpg",
        amount: 1,
    },
    {
        id: 6,
        title: "The Pragmatic Programmer",
        author: "by Andrew Hunt and David Thomas | 20 October 1999",
        price: 400,
        img: "https://m.media-amazon.com/images/I/51yaxPX4BFL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_PIStarRatingFOURANDHALF%2CBottomLeft%2C360%2C-6_SR600%2C315_ZA118%2C445%2C290%2C400%2C400%2CAmazonEmberBold%2C12%2C4%2C0%2C0%2C5_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg",
        amount: 1,
    },
    {
        id: 7,
        title: "Introduction to Algorithms",
        author: "by Thomas H. Cormen | 1 July 2009",
        price: 550,
        img: "https://m.media-amazon.com/images/I/61ZYxrQEpCL._AC_UF1000,1000_QL80_.jpg",
        amount: 1,
    },
    {
        id: 8,
        title: "Eloquent JavaScript",
        author: "by Marijn Haverbeke | 14 December 2014",
        price: 120,
        img: "https://eloquentjavascript.net/img/cover.jpg",
        amount: 1,
    },
    {
        id: 9,
        title: "You Don't Know JS",
        author: "by Kyle Simpson | 27 December 2014",
        price: 220,
        img: "https://m.media-amazon.com/images/I/817kywRJjVL._AC_UF1000,1000_QL80_.jpg",
        amount: 1,
    },
    {
        id: 10,
        title: "Cracking the Coding Interview",
        author: "by Gayle Laakmann McDowell | 1 July 2015",
        price: 450,
        img: "https://5.imimg.com/data5/UZ/XB/DX/SELLER-99655515/cracking-the-coding-interview-book.jpg",
        amount: 1,
    },
    {
        id: 11,
        title: "Design Patterns",
        author: "by Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides | 21 November 1994",
        price: 300,
        img: "https://refactoring.guru/images/patterns/book/web-cover-en.png",
        amount: 1,
    },
    {
        id: 12,
        title: "Refactoring",
        author: "by Martin Fowler | 8 March 1999",
        price: 320,
        img: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1386925632i/44936.jpg",
        amount: 1,
    }
];

export default list;
